### ISSUE TITLE
Copy Command Button on Linux Ubuntu Mate 18.04 

### ISSUE THREAD

**Issue by nocheinlarry** [MicrosoftDocs/azure-docs-cli#1196]
Change package-list and assigned Copy Button on Linux doesn't copy all script lines. Only first line works.

Refering to Install // 1 // Update package-lists

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Installieren der Azure CLI unter Linux mit apt](https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-apt?view=azure-cli-latest#install)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/azure/azure-docs-cli-python.de-DE/blob/live/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@nocheinlarry I investigated the problem further. On Ubuntu Bionic, in Firefox, the "copy" button on the site will copy all of the text in the box. However, the first invocation of `sudo` requires user input, which eats the remaining paste of the text due to how terminal works. I'm unsure of how to resolve this problem but you can work around it by copying each line one at a time and pasting it in, instead of using the site `Copy` button.
