### ISSUE TITLE
Step 3 failing on WSL with error "gpg: keyserver receive failed: No dirmngr"

### ISSUE THREAD

**Issue by akkensheen** [MicrosoftDocs/azure-docs-cli#1288]
It would be great if you just add this link: https://github.com/Microsoft/WSL/issues/3286#issuecomment-402594992 or copy comment text to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#cli-fails-to-install-or-run-on-windows-subsystem-for-linux
Because it solves issue and there is no reason to force people search it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#cli-fails-to-install-or-run-on-windows-subsystem-for-linux)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@akkensheen - As the linked issue states, this was "Fixed in 1809". The correct solution here is to update to a more recent version of Windows (and WSL), as described in the [troubleshooting](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#cli-fails-to-install-or-run-on-windows-subsystem-for-linux) section.
