### ISSUE TITLE
Problems authenticating as a service principal (with a key/certificate) using azurecli

### ISSUE THREAD

**Issue by TitaniumDave** [MicrosoftDocs/azure-docs-cli#1336]
The article steps under **Sign in for a service principal** (with a certificate issued from a 2-tier PKI) are dubious for several reasons, apart from the wording being confusing it doesn't appear to work using **az cli** (2.0.59) on macOS (10.14) or Windows 10 Enterprise (v1809). The command used is below:

`az login --service-principal --username APP_ID --tenant TENANT_ID --password /path/to/cert`

1) The wording is ambiguous. Passwords are not associated with a certificate they are associated with an encrypted private key (PEM format in this case) or PKCS#12 file, so the article should be reworded to be clearer about what exactly the input format is!

Is the input a PKCS#8 encoded private key, either unencrypted or encrypted, or is it a PKCS#12 (PFX) file with the complete PKI chain of trust as well as service principal certificate?

For the [PowerShell equivalent](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-authenticate-service-principal-powershell) of these steps the input is a PKCS#12 file sourced from either a local file, the Windows Certificate store or Azure Key Vault and I can confirm this works (using the certificate store at least)

2) Whether using macOS or Windows when using the **az** steps I get Python errors (see attached).

3) It's not clear from the article whether [these](http://masterandcmdr.com/add-azure-ad-trusted-certificate-authority/) steps need to be followed in order to trust a corporate root certificate into AAD for service principal authentication, and if so whether an OCSP AIA location can be used as the **crlDistributionPoint**?

Please advise, let me know if you need any more information from me and whether I am doing some wrong with the **az cli** steps.

[Azure-SP-CertAuth-050319.txt](https://github.com/MicrosoftDocs/azure-docs-cli/files/2942653/Azure-SP-CertAuth-050319.txt)

**Comment by sptramer** [comment]
@TitaniumDave Sorry for the delay in response, but this issue requires some more investigation. My understanding is that you only need to be holding the private key portion of the certificate in order to log in, but that it must be in a base64-encoded text-only format for the CLI at this time. I believe that a PEM is fine. You shouldn't need a full trust chain installed as I don't believe the CLI performs validation of the sign-in certificate and any trust chain validation would happen on Azure (which should already have a CA authority trust chain available.)

I've taken a backlog item to make sure that this article is clearer based on your feedback. Please let me know if you have other questions.

**Comment by TitaniumDave** [comment]
Hi @sptramer, 

No problem with the delay, thanks for the response!

> My understanding is that you only need to be holding the private key portion of the certificate in order to log in, but that it must be in a base64-encoded text-only format for the CLI at this time. I believe that a PEM is fine.

Yes, a Base64 RSA private key (PEM file) is fine, but as mentioned above only an _unencrypted_ RSA private key actually works. The input should accept wrapped RSA private keys as detailed below:

https://github.com/kjur/jsrsasign/wiki/Tutorial-for-PKCS5-and-PKCS8-PEM-private-key-formats-differences

> You shouldn't need a full trust chain installed as I don't believe the CLI performs validation of the sign-in certificate and any trust chain validation would happen on Azure (which should already have a CA authority trust chain available.)

Fair enough I think [the article](http://masterandcmdr.com/add-azure-ad-trusted-certificate-authority/) I read about that is a red herring.

I agree that at the point you create the service principal and associate a certificate only the correct private key associated with that certificate can be used for authentication, and and PKI trust hierarchy is irrelevant.

**Comment by sptramer** [comment]
@TitaniumDave I'm going through older unresolved issues and noticed this one. From your response it sounds like there's an issue with the data formats the CLI accepts - you'll need to file a [bug report/feature request](https://github.com/azure/azure-cli) to see if they can offer support. My understanding is that the types of PEM allowed may be limited by what AAD/Key Vault supports.

Going to close since I don't think I can offer any more help.
