### ISSUE TITLE
Incomplete prerequisites

### ISSUE THREAD

**Issue by mbialecka** [MicrosoftDocs/azure-docs-cli#1350]
The instructions didn't work for me. After trying numerous combinations of different dependencies versions (I don't have to tell you how much time it took), the installation script finally worked when I installed python-dev package. Please check and update prerequisites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI for Linux manually](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-linux.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
You were following the manual install instructions, which correctly point out Python as a dependency. Because these instructions are intended for users running on a distribution which isn't supported by any other installer, `python-dev` cannot be listed as a prerequsite. Instead, Python is correctly identified as a dependency, and installing from a source other than a package manager will include the development libraries.

**Comment by mbialecka** [comment]
I don't understand this explanation. These instructions don't work for me. Please update instructions so they can be successfully followed. 

I've tried instructions with package manager which didn't work for me, that's why I turned to manual installation.

**Comment by sptramer** [comment]
The manual instructions link to Python manual installs, which would be the appropriate install method for users on LFS. Users with unsupported distributions should also be familiar enough with their platform to figure out which Python packages to install to get the proper support.
