### ISSUE TITLE
Install step 2 makes 'apt-get update' fail in my Ubuntu 18.04 machine

### ISSUE THREAD

**Issue by ecejjar** [MicrosoftDocs/azure-docs-cli#1353]
The URL to the update site (https://packages.microsoft.com/repos/azure-cli ) fails TLS negotiation when running 'apt-get update'. If I use the 'http://' URL instead of 'https://', it works.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-gb/cli/azure/install-azure-cli-apt?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@ecejjar Can you please provide the TLS negotiation error, so that I can see if this is due to an expired certificate?

**Comment by gstolz** [comment]
I also have problem with the installation on Ubuntu 18.04 (WSL). But this instruction helped:
https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-apt.md
After manually downloading gpg key everyhting worked fine.

**Comment by ecejjar** [comment]
$ sudo apt-get update
Ign:1 https://packages.microsoft.com/repos/azure-cli cosmic InRelease
Err:2 https://packages.microsoft.com/repos/azure-cli cosmic Release                       
  Could not handshake: The TLS connection was non-properly terminated. [IP: 172.22.232.100 8080]

**Comment by sptramer** [comment]
@ecejjar Unfortunately that doesn't give me enough information to be able to resolve your problem. You could be located behind a proxy or have other mediation issues which prevent you from connecting with SSL to the Microsoft packages site. Please talk to your system administrator to resolve them.

You can also try the [updated Ubuntu instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest) and see if your problem is resolved.
