### ISSUE TITLE
the tutorials show using query, but query args are single-quoted by mistake

### ISSUE THREAD

**Issue by carehart** [MicrosoftDocs/azure-docs-cli#1438]
Folks, in the CLI tutorial pages (such as https://docs.microsoft.com/en-us/cli/azure/azure-cli-vm-tutorial?tutorial-step=4&view=azure-cli-latest), it shows use of the `--query` arg for a command like `az show`, but the query argument is mistakenly show as being single-quoted:

`--query 'networkProfile.networkInterfaces[].id'`

That just treats the arg as a string, and returns that string itself as the result, not the evaluated value of that named element. 

Instead, the arg should be **double-quoted** (or not quoted at all, as long as there is no space in the name of the arg).

This is true as well on the next step (5) of the tutorial. Indeed, it would seem that someone on the doc team should endeavor to find any cases in any of the CLI docs where the `--query` arg is followed by a single quote, to assess if it should be a double-quote instead.

**Comment by sptramer** [comment]
@carehart The query is in fact treated as a string, because it's passed through to the CLI and not meant to be evaluated in-shell. Double-quote behavior for arguments which include shell-interpreted behavior such as `[]` case misbehavior in some versions of `bash` and `bash`-dervied shells, such as `zsh`. If you are working on PowerShell, please keep in mind that site examples are written for `bash`.
