### ISSUE TITLE
Installing Azure CLI on Debian bionic does not work

### ISSUE THREAD

**Issue by kuntergunt** [MicrosoftDocs/azure-docs-cli#1518]
When doing the first step (curl -sL ...)  I already get an error:

E: The repository 'https://packages.microsoft.com/repos/azure-cli buster Release' does not have a Release file.

**Comment by sptramer** [comment]
Your output indicates that you're running Debian Buster, not Ubuntu Bionic. Buster is not currently one of the supported distributions. Since you're using an unsupported distribution, follow the [Troubleshooting - No package for your distribution](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#no-package-for-your-distribution) steps.

There is currently no ETA for a Buster package but the install compatibility section will be updated when it is available.
