### ISSUE TITLE
Need guidance on lifecycle management

### ISSUE THREAD

**Issue by Roblarson** [MicrosoftDocs/azure-docs-cli#1561]
The article is incomplete from a lifecycle management perspective to reduce security threats. How do you query for SPNs that are not in use so you can remove them? How do you determine if credentials have not been used in X days and need to be reset or deleted?  etc. 

Need to provide this guidance so enterprises can properly reduce threat vectors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f84bdc-9ed0-eb85-f3af-9711e8083a95
* Version Independent ID: 03a47d06-5fbf-4764-0882-99cd8bd41110
* Content: [Use Azure service principals with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?toc=%2Fazure%2Fazure-resource-manager%2Ftoc.json&view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md)
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This article is meant to just be a short introduction to setting up service principals and not a full guide to using application ID/service principals for security purposes. The correct, in-depth source for that material is the [Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/) documentation. 

It looks like that service is not directly linked anywhere from this article, so I will make sure that users can be correctly directed there.

**Comment by dbradish-microsoft** [comment]
@Roblarson , the following links have been added to the Azure CLI article and are being given here for your reference.  

* [Application and service principal objects in Azure Active Directory](/azure/active-directory/develop/app-objects-and-service-principals)
* [How to: Use the portal to create an Azure AD application and service principal](/azure/active-directory/develop/*owto-create-service-principal-portal)
* [How to manage service principals](/azure/developer/python/how-to-manage-service-principals)

This issue is being closed as the Azure CLI Microsoft Docs issue has been resolved within the intent of the article.  I encourage you to use the [MicrosoftDocs/azure-docs](https://github.com/MicrosoftDocs/azure-docs/issues) for feedback on Azure Active Directory documentation.

Kindly,

Delora
