### ISSUE TITLE
When will it support - MacOs Catalina ?

### ISSUE THREAD

**Issue by swapnild2111** [MicrosoftDocs/azure-docs-cli#1616]
I have updated my macos and now `az aks` no longer works. When will it work for Catalina macos?

**Comment by sptramer** [comment]
This repo is for documentation issues only. This sounds like you're experiencing a bug on macOS, most likely related to the new code-signing requirements on the system or other sandboxing that prevents AKS from working correctly. In order to get the problem addressed, please [file an issue with engineering](https://github.com/Azure/azure-cli/issues/new/choose).
