### ISSUE TITLE
Upgrade Request

### ISSUE THREAD

**Issue by thegreatpeon** [MicrosoftDocs/azure-docs-cli#1710]
It seems like it would be pretty straight forward to simply put an "az -update" command in the program that does this for you. That would be a much less confusing process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by kobulloc-MSFT** [comment]
@thegreatpeon I agree, that would be a lot more intuitive.  The best place for suggestions to be seen is https://feedback.azure.com/forums/216665-scripting-and-command-line-tools.  Let us know when you post feedback, so that we can vote on it.

We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
