### ISSUE TITLE
Long summary is not part of the auto generated documentation

### ISSUE THREAD

**Issue by atbagga** [MicrosoftDocs/azure-docs-cli#1794]
We have got multiple issues of missing help when people are referring to the docs.microsoft.com documentation for the command. 

Even when the same is present in the long summary of the command. 
e.g. 
![image](https://user-images.githubusercontent.com/11888714/73842612-eb3e6e00-4842-11ea-8317-7c8da364dc25.png)

**Comment by BhargaviAnnadevara-MSFT** [comment]
@atbagga Thanks for the feedback! We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@atbagga I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Working through open GitHub issues, this issue has been open since Feb 5.  @fengzhou-msft, is this still a problem?  Here are screenprints of the current state on 10/16/2020:

**The link that is referenced in the --help:**
https://docs.microsoft.com/en-us/azure/devops/cli/service-endpoint?view=azure-devops#create-service-endpoint-using-configuration-file

**Screenprint of auto-generated reference content:**
https://docs.microsoft.com/en-us/cli/azure/devops/service-endpoint?view=azure-cli-latest#az_devops_service_endpoint_create
![image](https://user-images.githubusercontent.com/58762114/96311275-f777ef00-0fbd-11eb-97ec-63eb840cec24.png)

**Screenprint of Azure Cloud Shell output:**
![image](https://user-images.githubusercontent.com/58762114/96311776-188d0f80-0fbf-11eb-9ec6-a35f486eaa90.png)
