### ISSUE TITLE
Breaking changes in minor releases

### ISSUE THREAD

**Issue by estensen** [MicrosoftDocs/azure-docs-cli#1929]
Not sure if this is the right place to file this issue, but from looking at the [release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md) it seems that minor releases contain breaking changes.
Is there any reason for this?

**Comment by TravisCragg-MSFT** [comment]
@estensen Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
@chenlomis, please respond with product management insight.  Thank you.

**Comment by chenlomis** [comment]
Hi @estensen, thank you for your inquiry

One major reason of why the CLI team doesn't bump up the major version of every breaking change is because we release fairly frequently - every 3 weeks . And each release often contains breaking changes. In fact, due to our frequent release, in the past we'd only been bumping patch version for each release such as 2.066 to 2.067

Another reason is that we view CLI 2.x as our new brand ever since the CLI V2 came out

@estensen , is there any particular concern from your end? I'd love to channel your thoughts and expectation back to your team

Thank you

**Comment by estensen** [comment]
@chenlomis using [semver](https://semver.org/) for versioning you imply that there's a contract of not introducing breaking changes on minor updates. It is implied that new features are added, but that it's safe to upgrade without making code changes. It greatly decreases the mental overhead of keeping dependencies up-to-date. I would appreciate if it was added an explicit note that semver is not used or that the date of the update is used as the version number instead. This would make it a lot easier to depend on the Azure CLI :)

**Comment by chenlomis** [comment]
Thank you for the elaboration @estensen , our team will work together on a a more explicit communication plan/solution and get back to you

**Comment by dbradish-microsoft** [comment]
@estensen / @chenlomis ,

I am closing this issue as this concern has been brought to the attention of the engineering team.  While the Azure CLI continues its rapid growth (over 100 new Azure CLI commands were released last week), we have to mix all types of changes in our bi-weekly releases.  As with all Microsoft products, this is not a common or desired scenario, and we anticipate settling into separate minor and breaking change release as the product matures,
