### ISSUE TITLE
How do I install older versions of the cli?

### ISSUE THREAD

**Issue by zumiek** [MicrosoftDocs/azure-docs-cli#1954]
Working on a project where previous developer used an older version of the cli, but now when I try to run the scripts he created it's not working.
I fully understand the ramifications of running an older cli, but the costs incurred for customer for me to fix all the issues is not acceptable, and I can't really find where the older versions of the installers are?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Service: **azure-cli**
* GitHub Lo

**Comment by MonikaReddy-MSFT** [comment]
@zumiek , Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
Hello @zumiek , 
Thanks for reaching out to us and for being patient. 
Can you please provide the specific version that you are looking for? So, we can try to find the old MSI and share it with you.

I have opened up a new issue in PG CLI Repo, so they can track your issue and get it taken care of. 

At this moment, I will go ahead and close this request but I will work with you until your issue is resolved, Meanwhile please provide me the above details, so I can circulate it back to Product team. 
.

**Comment by MonikaReddy-MSFT** [comment]
@zumiek , PG has responded with the following : 


Package | Install Specific Version Command
-- | --
RPM | yum --showduplicates list azure-cli; sudo yum install azure-cli-2.2.0-1.el7
DEB | apt-cache policy azure-cli; sudo apt-get install azure-cli=2.2.0-1~bionic
MSI | Invoke-WebRequest -Uri https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.2.0.msi -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
HOMEBREW | brew install -s https://raw.githubusercontent.com/azclibot/homebrew-core/azcli2.2.0/Formula/azure-cli.rb
PIP | pip install azure-cli=2.2.0
DOCKER | docker pull mcr.microsoft.com/azure-cli:2.2.0


I hope this helps.
