### ISSUE TITLE
Question on formatting to return a single value

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/azure-docs-cli#1989]
example statement fails in Bash script:
```bash
var=$(
az monitor app-insights component create --app $someName
)
```
I'm not sure if it's my formatting of the "( )" or if I cannot accept variables inside this statement?  Do we have documentation on this?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e60c12ef-d293-5626-c7aa-c7e9241bf975
* Version Independent ID: 7acca1dd-b735-7e1f-afd9-2b5b6ea06b1c
* Content: [Query command results with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/query-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/query-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by kobulloc-MSFT** [comment]
@awentzel Thank you for the feedback!  We are investigating this and will get back to you shortly.

**Comment by awentzel** [comment]
The issue appears to be that when wrapping "( )" into new lines it breaks the formatted and variables are no longer recognized.  When in the same line the issue no longer exists.  The error was generic and seemingly unrelated so I didn't realize this until trying a few different things.  It might be nice to update documentation if it does not already exist to show a couple more complex examples.  It's not very readable to have a lot of arguments in a single line.  Wrapping would be more maintainable.

**Comment by kobulloc-MSFT** [comment]
@awentzel Thank you for your feedback and thank you again for posting your solution!  Since the CLI covers so much ground in Azure, it can sometimes be challenging to track down specific examples.  For multi-line commands you can use the "\" character like this:

https://docs.microsoft.com/en-us/azure/batch/scripts/batch-cli-sample-run-job#example-script

```
# Create a general-purpose storage account in your resource group.
az storage account create \
    --resource-group myResourceGroup \
    --name mystorageaccount \
    --location westeurope \
    --sku Standard_LRS
```

Additionally, I believe there are some scenarios where a [different character is used](https://stackoverflow.com/questions/57562449/how-to-split-a-cli-command-in-azure-devops-over-multiple-lines-running-on-wind), like "`" or "^".

We take user feedback on generic errors and I would love to see those improved as they are difficult to troubleshoot.  You can post feedback that will get reviewed by the product group here:

https://feedback.azure.com/forums/216665-scripting-and-command-line-tools

**Comment by kobulloc-MSFT** [comment]
@awentzel We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
