### ISSUE TITLE
sign in without listing all subscriptions

### ISSUE THREAD

**Issue by diepnt90** [MicrosoftDocs/azure-docs-cli#2148]
[Enter feedback here]

Hi,

My account has lots of subscriptions so listing up all subscription after signing will take time and occupies all my screen.

Any argument to ignore that?

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by HarshitaSingh-MSFT** [comment]
@diepnt90 , could you please share a screenshot of this issue which you are facing?

**Comment by HarshitaSingh-MSFT** [comment]
@diepnt90, Just checking in to see if you have had a chance to see the previous response.

**Comment by diepnt90** [comment]
@HarshitaSingh-MSFT Please check the screenshot. I just want to login. no need to list all my subscriptions (~300). It needs time and I don't want to wait. So if any agreement to ignore the listing is great.
![Capture](https://user-images.githubusercontent.com/18731180/91251859-8454b800-e786-11ea-82d3-9f6a036a3c4e.JPG)

**Comment by HarshitaSingh-MSFT** [comment]
@diepnt90 , we do not have a parameter for this reference that will suppress the default Azure CLI output.

**Comment by dbradish-microsoft** [comment]
@fengzhou-msft , please note customer request for engineering consideration.  Thank you.

**Comment by fengzhou-msft** [comment]
@diepnt90 you can use `az login --output none`

**Comment by jiasli** [comment]
If you only want to ignore the output, you may use

```sh
# Work for all platforms
az login --output none

# Linux
az login > /dev/null

# PowerShell
az login > $null

# CMD
az login > $NUL
```

If you want to skip the whole **listing tenants** and **listing subscriptions** operations, the current version of Azure CLI doesn't support it. 

In the [Beta release](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli#azure-cli-beta-version) which uses MSAL, we added a new parameter `--tenant-access` to `az login` to bypass **listing tenants** and **listing subscriptions** operations. But then if you want to invoke any ARM request, you will have to provide the `--subscription` parameter, because CLI doesn't know which subscription is currently selected.

**Comment by HarshitaSingh-MSFT** [comment]
Thank you @jiasli for responding and creating the issue!
CC: @diepnt90

**Comment by HarshitaSingh-MSFT** [comment]
@diepnt90 , can we close this issue? Are you happy with the resolution?

**Comment by HarshitaSingh-MSFT** [comment]
Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply and we will gladly continue the discussion.

**Comment by diepnt90** [comment]
@HarshitaSingh-MSFT Thank you all.
