### ISSUE TITLE
Azure Load Balancer Read Access using the Policy

### ISSUE THREAD

**Issue by z003smvh** [MicrosoftDocs/azure-docs-cli#2197]
Hi Team,

I have posted my query on Azure Q&A and got no response yet from Azure Policy team. 

https://docs.microsoft.com/en-us/answers/questions/102039/azure-load-balancer-read-access-using-azure-policy.html?childToView=103568#answer-103568

I suggest your response on the below query once again.

"parameters": {},
 "policyRule": {
 "if": {
 "field": "type",
 "equals": "Microsoft.Network/LoadBalancers"
 },
 "then": {
 "effect": "deny"
 }
 }

Instead of using "DENY" what could be my options to select. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by SwathiDhanwada-MSFT** [comment]
@z003smvh Thanks for your comment. We will review the issue and get back to you shortly.

**Comment by SwathiDhanwada-MSFT** [comment]
@z003smvh As mentioned in Q&A post, you can use [Dynamic Groups](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-dynamic-membership) feature of AD to achieve your requirement. 

As there are no further documentation changes, we will close the issue here. If there are further questions , please revert and we can continue our conversation on the Q&A post.
