### ISSUE TITLE
Defaults not accepted for all commands

### ISSUE THREAD

**Issue by Makovec** [MicrosoftDocs/azure-docs-cli#2259]
When I set defaults, I assume, that if will work for all commands, but it is not true.

Try this:

```
az configure -d group=tstgrp001-rg
az configure -d location=westeurope
az group create
```

It will return error:

```
RequiredArgumentMissingError: the following arguments are required: --name/--resource-group/-n/-g
Try this: 'az group create --location westeurope --resource-group MyResourceGroup --subscription mysubscription'
Still stuck? Run 'az group create --help' to view all commands or go to 'https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest' to learn more
```

I just updated to the latest version 2.14.0

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Makovec Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Makovec Yes, I see the same behavior as well. This seems to be a bug with the CLI.

I've opened a bug with the Azure CLI repo for our Engineering Team to look at. Please track the issue here: Azure/azure-cli#15724

We will now proceed to close this thread as this channel (the [Azure CLI Docs](https://github.com/MicrosoftDocs/azure-docs-cli) repository) is only for driving improvements related to the Azure CLI documentation. However, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
