### ISSUE TITLE
"az postgres flexible-server create" getting misspelled error

### ISSUE THREAD

**Issue by ksadineni13** [MicrosoftDocs/azure-docs-cli#2503]
az postgres flexible-server create --public-access all
**'create' is misspelled or not recognized by the system.**

az postgres flexible-server firewall-rule create
**'firewall-rule' is misspelled or not recognized by the system.**

Running below version
az version
{
  "azure-cli": "2.21.0",
  "azure-cli-core": "2.21.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "db-up": "0.2.1",
    "rdbms-connect": "0.1.2"
  }
}

Output: az postgres: 'flexible-server' is not in the 'az postgres' command group.

**Comment by MartinJaffer-MSFT** [comment]
Thank you for bringing this to our attention, @ksadineni13  .  To better assist you, could you please identify which document this is in reference to?

**Comment by MonikaReddy-MSFT** [comment]
@ksadineni13 -  Can you please share with us the URL of the document that you are having issues with?
Please note that we scope issues on this repo to feedback related to the docs. If you have a product question, please post it on Microsoft QnA or Stack Overflow. Thank you for your understanding.

**Comment by ksadineni13** [comment]
Thank you for getting back to me on this. Sorry was out for few days. So the issue I am having is when running 
< _**az postgres flexible-server create**_ >    I keep getting below error and I know I am using latest version for az cli "2.21.0". Not sure what else I am missing. 
**'create' is misspelled or not recognized by the system.**
![Uploading Screen Shot 2021-04-06 at 7.09.20 PM.png…]()

**Comment by ksadineni13** [comment]
https://docs.microsoft.com/en-us/cli/azure/postgres/flexible-server?view=azure-cli-latest#az_postgres_flexible_server_create 

That is the documentation I am referring to.

**Comment by MonikaReddy-MSFT** [comment]
@ksadineni13 - Sure, thank you for the info. I will get back to you shortly.

**Comment by dbradish-microsoft** [comment]
@ksadineni13, Can you please share a screen print of your full command-line syntax and resulting error so we can replicate the problem?  Also please kindly share the operating system and tool you are using: command line, PowerShell, Azure Cloud Shell on Windows, Linux, macOS etc.  

In testing this reference command via Azure Cloud Shell, I am receiving expected results, so we need a similar screen print from you in order to assist. Thank you.
![image](https://user-images.githubusercontent.com/58762114/114192341-5db14f00-991b-11eb-8346-dc47127d75a4.png)

**Comment by ksadineni13** [comment]
Thank you for taking a look at this. Yes it works for me on azure cloud shell, but it does not work from my local machine. I am using Mac, I get the same error when running form mac terminal and also VS code terminal. Attaching screen shots. 
![Screen Shot 2021-04-09 at 10 30 56 AM](https://user-images.githubusercontent.com/40213688/114219183-3066a000-991f-11eb-80bb-47876665755b.png)
![Screen Shot 2021-04-09 at 10 36 15 AM](https://user-images.githubusercontent.com/40213688/114219447-863b4800-991f-11eb-997a-396e89c88628.png)

**Comment by DaeunYim** [comment]
Hi @ksadineni13 
Thanks for reaching out to us. 
Unfortunately, I couldn't reproduce the same error in Mac OS. 

Could you try out these things?
- Run az upgrade
- re-install azure-cli 
- Remove extensions 

Also, try running
"az postgres --help"
"az postgres flexible-server --help" to see what commands groups are there?

**Comment by MonikaReddy-MSFT** [comment]
@daeunyim - Thank you for providing your insights.
@ksadineni13 - I hope @daeunyim has answered your question. Please try the above and see if it helps.
At this moment, Since there is no doc update required, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by RyanHill-MSFT** [comment]
test comment
