### ISSUE TITLE
Export Output to a file in Azure CLI

### ISSUE THREAD

**Issue by sandeepraichura** [MicrosoftDocs/azure-docs-cli#2613]
[Enter feedback here]
Does CLI support exporting output to a file similar to PowerShell ?  If it does, can you add examples ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48273ba7-da5a-95f0-7ffc-8c6d5282313d
* Version Independent ID: 83d348f9-fd1f-1041-0304-d8634e5526d4
* Content: [Output formats for Azure CLI](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli)
* Content Source: [docs-ref-conceptual/format-output-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/format-output-azure-cli.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@sandeepraichura Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@sandeepraichura Azure CLI does not support exporting to a file as an option with the `--output` parameter, if that was the intent of the question. The current supported formats are `json`, `jsonc`, `yaml`, `table`, `tsv` and `none`, as mentioned in the linked article.

However, since Azure CLI can be run across platforms, here are a few options you can use:
```
# Using the file redirection operator (>)
az vm list > out.json

# Using Out-File cmdlet (PowerShell environments only)
az vm list | Out-File out.json
```
Adding @dbradish-microsoft for any additional insights if this ask was ever considered for Azure CLI.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@sandeepraichura Hope the above inputs help. Are there any further questions here?

**Comment by BhargaviAnnadevara-MSFT** [comment]
@sandeepraichura We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
