### ISSUE TITLE
Please demo Error handling

### ISSUE THREAD

**Issue by mikeblakeuk** [MicrosoftDocs/azure-docs-cli#2749]
Please demo Error handling

What is the recommended way to handle errors in powershell with az commands?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e51daa3-30c5-f449-36a1-9f33c70ca2fc
* Version Independent ID: a21e188b-4ff4-0aca-531b-d4b179665be1
* Content: [Use Azure CLI effectively](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively)
* Content Source: [docs-ref-conceptual/use-cli-effectively.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/use-cli-effectively.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mikeblakeuk Thanks for the question. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mikeblakeuk This would be an interesting scenario to handle. :)

Since Azure CLI commands escape PowerShell's `Try..Catch` mechanism, error handling here can be a little tricky. While running Azure CLI commands on PowerShell, I've found that checking on the [automatic variable](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.1#section-1) `$?` helps in determining the execution status of the command, as follows:

```
# Returns False as the command errors out
PS C:\> $output = az group create -g myRG | ConvertFrom-Json
if (!$?) {
    Write-Error "Error creating storage account"
}
else {
    Write-Output "RG created"
}

az : ERROR: the following arguments are required: --location/-l
At line:2 char:11

# Returns True as the command succeeds
PS C:\> $output = az group create -g myRG -l eastus | ConvertFrom-Json
if (!$?) {
    Write-Error "Error creating storage account"
}
else {
    Write-Output "RG created"
}

RG created
```

**Additional tip:**

To make Azure CLI suppress warnings and only show errors during command invocation, you could use the `only-show-errors` parameter as well so errors will be written to `stderr`. Be sure to set `$ErrorActionPreference` to `Stop` though.
```
$ErrorActionPreference = "Stop"
PS C:\> $output = az group create -g myRG | ConvertFrom-Json
if (!$?) {
    Write-Error "Error creating storage account"
}
else {
    Write-Output "RG created"
}
```

Having said all of that, documenting the recommended guidance on error handling with Azure CLI would indeed be a great enhancement to the already valuable [Use Azure CLI effectively](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively) article.

Hence I'm assigning the issue to the content author to evaluate and update the article as appropriate. Thanks again for the feedback. Hope the provided inputs help in the meantime. 😊

**Comment by BhargaviAnnadevara-MSFT** [comment]
@dbradish-microsoft @mikefrobbins - FYI.

**Comment by mikefrobbins** [comment]
By default, in PowerShell only terminating errors stop execution. For PowerShell code, specify the `ErrorAction` parameter with `Stop` as the value to turn a non-terminating error into a terminating one.

If you're using Azure CLI from PowerShell, you can't specify `ErrorAction` on the command itself. In that scenario, you would need to change the global `$ErrorActionPreference` variable as @BhargaviAnnadevara-MSFT mentioned. As a best practice, if you do change the value of the global `$ErrorActionPreference` variable, change it back to it original value after trying the command.

For more information about PowerShell error handling, see [Everything you wanted to know about exceptions](https://docs.microsoft.com/powershell/scripting/learn/deep-dives/everything-about-exceptions).

**Comment by dbradish-microsoft** [comment]
@mikeblakeuk, Thank you for your suggestion.  @BhargaviAnnadevara-MSFT, I have added this request to the Azure CLI docs backlog with a request completion date of October 2021.  With such, I am closing this GitHub issue.
