### ISSUE TITLE
"az network bastion create" throws error when "scale-units" parameter is not given

### ISSUE THREAD

**Issue by diongerritzen** [MicrosoftDocs/azure-docs-cli#2822]
According to the [docs](https://docs.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest#az_network_bastion_create) the required parameters of the `az network bastion create` command are `--name`, `--public-ip-address`, `--resource-group` and `--vnet-name`. However, running the command with just these four parameters results in the following error:
`'<' not supported between instances of 'NoneType' and 'int'`

This can apparently be resolved by adding the _optional_ parameter `--scale-units`.

Azure CLI version 2.30.0

**Comment by BhargaviAnnadevara-MSFT** [comment]
@diongerritzen Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@diongerritzen Thank you for bringing this to our attention. I'm able to reproduce the error you're seeing.

This is certainly not the expected behavior though. I've created a [bug report](https://github.com/Azure/azure-cli/issues/20289) with the **Azure/azure-cli** repository so our Azure CLI Engineering Team can take a look and fix. Please follow further updates to this issue on the same thread. Updates to docs would follow accordingly. Thanks again for the feedback.

**Comment by UmarMohamedUsman** [comment]
I see this issue is closed but still getting same error "'<' not supported between instances of 'NoneType' and 'int'". And this error is confusing and misleading. 
Once I provide --scale-units which is an optional param, it works.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@UmarMohamedUsman This was indeed fixed and released as part of the latest version of Azure CLI available today, i.e., version **2.31.0** ([release notes here](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli#network)). Not sure of the version you are seeing this with, but do try upgrading to the latest version and check if the issue persists.

If you still run into issues, please try commenting your findings [here](https://github.com/Azure/azure-cli/issues/20289) or open a new issue with the Azure/azure-cli repository with the detailed error logs.
