### ISSUE TITLE
testUpdates 

### ISSUE THREAD

**Issue by haaami01** [MicrosoftDocs/azure-docs-cli#2891]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI on Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/install-azure-cli-linux.md)
* Service: **azure-cli**
* GitHub Login: @dbradish-microsoft
* Microsoft Alias: **dbradish**

**Comment by JamesTran-MSFT** [comment]
@haaami01 
From the title of your issue and since there isn't any feedback, I'm assuming this is a test and will go ahead and close out this issue.

If you have any feedback regarding our documentation, please let me know or feel free to create a new GitHub issue with what you'd like changed/enhanced.

Thank you for your time and patience!
