### ISSUE TITLE
Azure CLI versioning is inconsistent

### ISSUE THREAD

**Issue by qrilka** [MicrosoftDocs/azure-docs-cli#2951]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.33.0

### Link to affected document

https://docs.microsoft.com/ru-ru/cli/azure/release-notes-azure-cli

### Description of the documentation error

It looks like versioning of Azure CLI has some issues, specifically it looks like version 2.33.0 didn't get into at least 1 page and container repository, specifically:
* https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md in this repo lists the version 2.33.0 released 4 days ago
* https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli also mentions that version
* but there's no Docker image for that version - https://mcr.microsoft.com/v2/azure-cli/tags/list with 2.32.0 as the latest
* at the same time the Russian version of the release notes page on Azure docs only lists versions up to 2.32.0 - https://docs.microsoft.com/ru-ru/cli/azure/release-notes-azure-cli

### Suggested fix

Fix the inconsistency and any problems in the project release process which could produce those.

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your feedback. This has been assigned to the content owner and will be updated as appropriate.

**Comment by chasewilson** [comment]
Hey @qrilka, Thanks for the feedback here. 

We'll review the automation around our release notes. The versions date would normally be on the first but was pushed back due to the Chinese new year celebration and the engineering team wanted to ensure there would be support for a new version release.

2.33.0 has been released and is ready for use.

I'll be closing this for now but will link to this issue if a new issue needs to be created here or reopen if we think it's fitting. Feel free to respond here with any questions or feedback.

**Comment by qrilka** [comment]
Thanks for the quick feedback
