### ISSUE TITLE
Creating Service principal (manual)  not clear

### ISSUE THREAD

**Issue by matjung** [MicrosoftDocs/azure-docs-cli#3482]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.43.0

### Link to affected document

https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M05_L14_Enable_Dynamic_Configuration_and_Feature_Flags.html

### Description of the documentation error

Task2 The mapping between the output in step2 and input for step6 is not clear

### Suggested fix

Step6 Service Principal ID = Step2 output appId
Step6 Service Principal Key = Step2 output password
Step6 Tenant ID = Step2 output tenant

**Comment by YashikaTyagii** [comment]
@matjung 
Thank you for your feedback!

Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.

[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
