### ISSUE TITLE
Kaycoins Organizations GitHub Cloud GitHub Enterprises

### ISSUE THREAD

**Issue by Apple1D** [MicrosoftDocs/azure-docs-cli#4290]
Check out Outlook Lite, the new light and fast app built for all networks that combines email, calendar, and contacts.

Download it here: https://go.microsoft.com/fwlink/?linkid=2216232

**Comment by TPavanBalaji** [comment]
Thank you for your feedback!
Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
