### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by redashimself** [MicrosoftDocs/azure-docs-cli#4453]
### Type of issue

Code doesn't work

### Feedback

az cosmosdb sql container redistribute-partition-throughput --account-name account_name --database-name db_name --name container_name  --resource-group rg_name --target-partition-info 8=1200 6=1200]' --source-partition-info 9]'

`-target-partition-info 8=1200 6=1200]' --source-partition-info 9]'`

The `]'` symbols here seems like a typo, the brackets are not closed.

### Page URL

https://learn.microsoft.com/en-us/cli/azure/cosmosdb/sql/container?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cosmosdb/sql/container.yml

### Author

@dbradish-microsoft

### Document Id

ac38600c-6df4-5898-4bd7-fe880eb36819

**Comment by Naveenommi-MSFT** [comment]
@redashimself 
Thank you for bringing this to our attention.
I've delegated this to content author @dbradish-microsoft, who will review it and offer their insightful opinions.

**Comment by dbradish-microsoft** [comment]
@redashimself, Thank you for your feedback. Because this article's source isprovided by the engineering team, I am moving your feedback to Azure/azure-cli [new issue #29357](https://github.com/Azure/azure-cli/issues/29357). The CosmosDB engineering team can respond and make the needed update from there. Please continue this discussion in the new location.
