### ISSUE TITLE
az pipelines create cli notes for "Azure Repo" does not work

### ISSUE THREAD

**Issue by srijayam** [MicrosoftDocs/azure-docs-cli#4481]
### Type of issue

Code doesn't work

### Feedback

all comments are for documentation on https://learn.microsoft.com/en-us/cli/azure/pipelines , in specific notes related to "az pipelines create" for "Azure Repo" did not work for me.
- there are more "required" parameters than just --name, I suppose organization & project are mandatory. i was asked to explicitly specify by the azcli
- "--detect true" did not work for me.
- my command "az pipelines create --name 'pipeline_via_azcli' --description 'az pipeline via cli' --repository myrepo --branch main --repository-type tfsgit --organization https://dev.azure.com/myorg --project myproject --skip-first-run true" errors with "The controller for path '/terraform/_apis/pipelines/Templates/recommendedtemplates' was not found or does not implement IController.  Operation returned a 404 status code." Note: my other repos in the same project have main branch so using that instead of master as per documentation
- above command did not work when the repo was empty nor with files in the repo (README.md & azure-pipelines.yml)
- "--skip-first-run true" made no difference. probably because pipeline is not created

### Page URL

https://learn.microsoft.com/en-us/cli/azure/pipelines?view=azure-cli-latest#az-pipelines-create

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/pipelines.yml

### Author

@dbradish-microsoft

### Document Id

e79f2bc9-543d-9a14-a08c-911d037e108a

**Comment by dbradish-microsoft** [comment]
@srijayam, Thank you for your feedback; however, because this issue is on reference content, I've moved your GitHub issue to Azure/azure-cli where the `az pipeline` engineering team can respond to you.  Please see new GitHub issue [29458](https://github.com/Azure/azure-cli/issues/29458), and continue the discussion there.

Kindly add screen prints showing your full command syntax and resulting error in the new GitHub issue.  If you prefer, the output from `--debug` would be equally as helpful.
