### ISSUE TITLE
Optional paramter is not optional on "az aks command result"

### ISSUE THREAD

**Issue by devaughnsaxa** [MicrosoftDocs/azure-docs-cli#4687]
### Type of issue

Outdated article

### Feedback

The title is self explanatory I think.
When I run the command "az aks command result" without the parameter "--command-id -i", it complains that the parameter is missing. It makes sense, but the documentation still says it's Optional.

Updating the documentation would be nice.
Thanks

### Page URL

https://learn.microsoft.com/en-us/cli/azure/aks/command?view=azure-cli-latest#az-aks-command-result

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks/command.yml

### Author

@dbradish-microsoft

### Document Id

c2fa8e60-a5f3-2510-5162-772d99570647

**Comment by devaughnsaxa** [comment]
If that's the case, is it possible for me to create a PR myself to update the docs?

**Comment by dbradish-microsoft** [comment]
@devaughnsaxa, thank you for your feedback. My guess is that this parameter is conditional, and unfortunately, we don't have a 3rd parameter category right now. For example, a conditional parameter is when "if you don't supply {a}, then you must supply {b}" or similar logic.

I am going to move your feedback to the Azure/azure-cli GitHub repository so the AKS team and Azure CLI PM can have increased awareness of the issue. Customer feedback does impact development priorities, so your comment will have impact.

Regarding updating the reference content, these docs are generated from source code which is why the `--help` parameter has the same information as the reference article. Therefore, your feedback moved to engineering is the path to improvement.

Please continue this conversation in Azure/azure-cli GitHub issue [30107](https://github.com/Azure/azure-cli/issues/30107).

**Comment by devaughnsaxa** [comment]
Thank you @dbradish-microsoft !
Your explanation makes totally sense.
