### ISSUE TITLE
az monitor app-insights page typo

### ISSUE THREAD

**Issue by thomasRimmereide** [MicrosoftDocs/azure-docs-cli#4704]
### Type of issue

Typo

### Feedback

In `Command`-table there is a typo on the command `az monitor app-insights workbook identity` :  _Manage workbook idneity._

### Page URL

https://learn.microsoft.com/en-us/cli/azure/monitor/app-insights?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/app-insights.yml

### Author

@dbradish-microsoft

### Document Id

588219b1-1476-3a0a-4c78-bd4afb8aa08d

**Comment by dbradish-microsoft** [comment]
@thomasRimmereide, Thank you for bringing this to our attention. Because this reference doc originates in the source code, I have moved your feedback to Azure/azure-cli-extensions GitHub issue [8167](https://github.com/Azure/azure-cli-extensions/issues/8167) where the engineering team can respond and correct the spelling.
