### ISSUE TITLE
Typo: "Manag quota for Azure resource providers"

### ISSUE THREAD

**Issue by codingoutloud** [MicrosoftDocs/azure-docs-cli#4737]
### Type of issue

Typo

### Feedback

Near top of page: "Manag quota for Azure resource providers"

"Manag" should be "Manage"

### Page URL

https://learn.microsoft.com/en-us/cli/azure/quota?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/quota.yml

### Author

@dbradish-microsoft

### Document Id

3ec784bc-0bff-e794-2fc3-dcb3d0e14ee3

**Comment by TPavanBalaji** [comment]
@codingoutloud 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dbradish-microsoft** [comment]
Thank you, @codingoutloud, for bringing this to our attention. Because this reference doc content originates in the source code I've moved your feedback to Azure/azure-cli [#30269](https://github.com/Azure/azure-cli/issues/30269) where the engineering team can make the change. Please continue to followup in this new location.
